spring.application.name=virtual-threads-demo

management.endpoints.web.exposure.include=health,prometheus,metrics,info
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
